### ISSUE TITLE
fcitx-rime have new data dir

### ISSUE THREAD

**Issue by skychan** [rime/home#217]
With the new upgrade, fcitx-rime change its profile dir now from `~/.config/fcitx/rime` to `/usr/share/rime-data`, so that my old config is reset. Is there any solution to use old configs any longer?

**Comment by lotem** [comment]
I don't think fcitx-rime has any updates recently.
`~/.config/fcitx/rime` and `/usr/share/rime-data` are both used by all versions of fcitx-rime.

I'm not clear what exactly happened to you. The best guess I can make is that you upgraded data packages that are installed in `/usr/share/rime-data` and that overwrites/deprecates the copy of the same file in `~/.config/fcitx/rime`. This is by design: it allows fcitx-rime to use the latest version of pre-installed config files.

**Comment by skychan** [comment]
I don't know, but it seems that files in `~./config/fcitx/rime` are useless, I can only configure rime with `/usr/share/rime-data/default.yaml` now.

**Comment by lotem** [comment]
If the problem is still bothering you, please report to [fcitx-rime](https://github.com/fcitx/fcitx-rime/issues). Both directories should work, by design. Why they didn't work for you in fcitx-rime is beyond my knowledge.
