### ISSUE TITLE
Process Multiple default.custom.yaml

### ISSUE THREAD

**Issue by hftsai256** [rime/home#538]
In some cases I would like to split my `default.custom.yaml` into multiple files and let one override the others with lexicon order (same as `udev` or `fontconfig`). Therefore I can organize my custom definitions into hierarchical order such as:
```
00-default.custom.yaml
20-default.custom.pinyin_extension.yaml
40-default.custom.pinyin_patch.yaml
...
99-default.custom.interface.yaml
```
Is this possible to work out with the current structure?
Thanks

**Comment by lotem** [comment]
It's possible via using the `__patch` syntax.
But currently there is no established best practices.

See 
`patch_example_4` in https://github.com/rime/home/wiki/Configuration#%E8%A3%9C%E9%9D%AA

This method requires that the following code be added to the user copy of `default.yaml`:
```yaml
# default.yaml
__patch:
  - default.custom:/patch
  - default.custom.pinyin_extension:/patch
  # ...
```
If modifying `default.yaml` is not what you can/want to do, then you have to merge the patches' content into node `default.custom:/patch`, adding one extra level of indirection. This is how https://github.com/rime/plum do customizations at the moment (like [these recipes](https://github.com/rime/rime-custom)), but the code becomes harder to reason about and it doesn't always work correclty because of potential conflicts in the patch items.

Examples of patch-like Rime recipes:
https://github.com/rime/rime-emoji
https://github.com/rime/rime-custom

**Comment by hftsai256** [comment]
@lotem Thanks for your help. I have figured out how to properly patch my `default.yaml` with `__patch` syntax. I think we can close this issue.
